name: Keep Fork Up-to-date

on:
  schedule:
    - cron: '0 0 * * *'
    # scheduled once a day at midnight
  workflow_dispatch: # click the button on Github repo!

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for new release in fork
        id: check_fork_release
        run: |
          FORK_RELEASE=$(git ls-remote --tags https://github.com/smartive/stencil-patched.git | cut -d '/' -f 3 | sort -V | tail -n 1)
          echo "Latest fork release: $FORK_RELEASE"
          echo "fork_release_tag=$FORK_RELEASE" >> $GITHUB_OUTPUT

      - name: Fetch upstream changes
        run: |
          git remote add upstream https://github.com/ionic-team/stencil.git
          git fetch upstream
          git checkout main
          git merge upstream/main

      - name: Check for new release in upstream
        id: check_upstream_release
        run: |
          UPSTREAM_RELEASE=$(git ls-remote --tags https://github.com/ionic-team/stencil.git | cut -d '/' -f 3 | sort -V | tail -n 1)
          echo "Latest upstream release: $UPSTREAM_RELEASE"
          echo "upstream_release_tag=$UPSTREAM_RELEASE" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.check_fork_release.outputs.fork_release_tag != steps.check_upstream_release.outputs.upstream_release_tag
        run: |
          #Set up Git
          git config user.name 'CI-Robot'
          git config user.email 'mr.robot@smartive.ch'

          # Set up your branch for changes
          git checkout -b update-repo

          # Commit and push changes to your forked repository
          git add .
          git commit -m "chore: update repo with upstream release ${{ steps.check_upstream_release.outputs.upstream_release_tag }}"
          git push origin update-repo

          # Create Pull Request
          gh pr create --base main --head update-repo --title "chore: update repo with upstream release ${{ steps.check_upstream_release.outputs.upstream_release_tag }}" --body "update repo with the latest upstream release."
