name: Sync with Original Repo

on:
  schedule:
    - cron: '0 0 * * *' # runs once a day at midnight
  workflow_dispatch: # click the button on Github repo!

jobs:
  sync-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout forked repository
      uses: actions/checkout@v2
      with:
        repository: smartive/stencil-patched
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main

    - name: Setup git
      run: |
        git config --global user.name 'CI-Robot'
        git config --global user.email 'mr.robot@smartive.ch'
        
    - name: Add original repository as remote
      run: git remote add upstream https://github.com/ionic-team/stencil.git

    - name: Fetch original repository tags
      run: git fetch upstream --tags

    - name: Get latest tag
      id: get_latest_tag
      run: echo "::set-output name=tag::$(git describe --tags $(git rev-list --tags --max-count=1))"

    - name: Checkout and merge latest tag from original repo
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git checkout ${{ steps.get_latest_tag.outputs.tag }}
        git checkout -B main
        git pull upstream main
        git push origin main

    - name: Check and update package.json name field if needed
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        CURRENT_NAME=$(jq -r .name package.json)
        if [ "$CURRENT_NAME" = "@stencil/core" ]; then
          jq '.name = "@smartive/stencil-core"' package.json > tmp.json && mv tmp.json package.json
          git add package.json
          git commit -m "Update package name to @smartive/stencil-core"
          git push origin main
        else
          echo "Package name is already updated."
        fi

    - name: Create new tag in forked repository
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git tag ${{ steps.get_latest_tag.outputs.tag }}
        git push origin --tags

    - name: Publish to npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm install
        npm version ${{ steps.get_latest_tag.outputs.tag }}
        npm publish
