name: Fork Sync

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.9.0
        with:
          owner: smartive
          base: main
          head: main
          repo: $ionic-team/stencil
          pr_title: Fork sync with upstream
